# Generated by Django 6.0.4 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('dht22_temp', models.FloatField()),
                ('dht22_umid', models.FloatField()),
                ('dht22_ind_calor', models.FloatField()),
                ('mq2', models.FloatField()),
                ('bme280_temp', models.FloatField()),
                ('bme280_umi', models.FloatField()),
                ('bme280_press', models.FloatField()),
                ('bme280_alti', models.FloatField()),
                ('gy30_lux', models.FloatField()),
                ('gy30_class_lux', models.FloatField()),
                ('uv_gyml8511_uv', models.FloatField()),
                ('uv_gyml8511_tensao', models.FloatField()),
                ('uv_gyml8511_saida', models.FloatField()),
                ('mq137_ppm_media', models.FloatField()),
                ('mq137_ppm_instant', models.FloatField()),
                ('uvcjmcu_indiuv', models.FloatField()),
                ('mq3', models.FloatField()),
                ('mq4', models.FloatField()),
                ('mq7', models.FloatField()),
                ('pluvio_mm', models.FloatField()),
                ('anemo_vel_ms', models.FloatField()),
                ('anemo_vel_kmh', models.FloatField()),
                ('anemo_grau', models.FloatField()),
                ('anemo_direcao', models.FloatField()),
            ],
        ),
    ]
