# Generated by Django 6.0.4 on 2026-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WDS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='anemo_direcao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='gy30_class_lux',
            field=models.CharField(max_length=50),
        ),
    ]
